    # CLOUD connector Config file
    - lineinfile: dest=/usr/local/clues/bin/cloud/config.py regexp=^CONFIGURE_WN_TIMEOUT line="CONFIGURE_WN_TIMEOUT=1500"
    - lineinfile: dest=/usr/local/clues/bin/cloud/config.py regexp=^RUNNING_WN_TIMEOUT line="RUNNING_WN_TIMEOUT=500"

    # CLUES Config file
    - lineinfile: dest=/usr/local/clues/config.py regexp=^MAX_TIME_BOOT line="MAX_TIME_BOOT = 1600"
    - lineinfile: dest=/usr/local/clues/config.py regexp=^MAX_WAIT_JOB line="MAX_WAIT_JOB = 1600"
    - lineinfile: dest=/usr/local/clues/config.py regexp=^SWITCH_ON_BLOCKSIZE line="SWITCH_ON_BLOCKSIZE = 1"
    - lineinfile: dest=/usr/local/clues/config.py regexp=^TIME_TO_EVALUATE line="TIME_TO_EVALUATE = 30"
    
    # SLURM plugin installation
    - command: tar -xzf /tmp/{{PLUGIN_FILE}}.tar.gz -C /usr/local/clues/plugins creates=/usr/local/clues/plugins/{{PLUGIN_FILE}}
    - file: src=/usr/local/clues/plugins/{{PLUGIN_FILE}} dest=/usr/local/clues/plugins/slurm state=link

    # CLUES specific values for slurm plugin
    - lineinfile: dest=/usr/local/clues/config.py regexp=^MANAGERS line="MANAGERS=['slurm']"
    - lineinfile: dest=/usr/local/clues/config.py regexp=^NODES_AVAILABLE..pbs.. line="NODES_AVAILABLE['slurm'] = 0"
    # CLUES CLOUD specific values for slurm plugin
    - lineinfile: dest=/usr/local/clues/bin/cloud/config.py regexp=^CONFIGURE_FILE line="CONFIGURE_FILE = '/tmp/conf/slurmwn.yml'"

    # Configure slurm.conf file
    - name: configure compute nodes section of slurm.conf
      lineinfile: dest=/usr/local/etc/slurm.conf regexp='NodeName=' line='NodeName=wnone_[0-{{NNODES|int - 1}}] CPUs=1 State=UNKNOWN' state=present
    - lineinfile: dest=/usr/local/etc/slurm.conf regexp='PartitionName=' line='PartitionName=debug Nodes=wnone_[0-{{NNODES|int - 1}}] Default=YES MaxTime=INFINITE State=UP' state=present

    # start SLURM slurmctld daemon
    - command: slurmctld
